name: Deploy Banking Infra

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, prod]

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=envs/${{ matrix.environment }} init

      - name: Terraform Plan
        run: terraform -chdir=envs/${{ matrix.environment }} plan

      - name: Terraform Apply
        run: terraform -chdir=envs/${{ matrix.environment }} apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}